### ISSUE TITLE
Make Foxy release

### ISSUE THREAD

**Issue by gbartyzel** [gbartyzel/ros2_net_ft_driver#7]
Adjust the code to be compatible with `Foxy` and make a release.

**Comment by tianjiawen1** [comment]
hi guys,
when i use build the package on humble, there was some mistake:
In file included from /home/tian/tjwws/src/ros2_net_ft_driver/net_ft_driver/src/hardware_interface.cpp:29:
/home/tian/tjwws/src/ros2_net_ft_driver/net_ft_driver/include/net_ft_driver/hardware_interface.hpp:71:35: error: ‘hardware_interface::return_type net_ft_driver::NetFtHardwareInterface::read()’ marked ‘override’, but does not override
how can i fix it?

**Comment by gbartyzel** [comment]
Hi, thanks for reporting this issue. It has been a long time since I was using this code. I'll check this today and fry to fix

**Comment by gbartyzel** [comment]
@tianjiawen1 Are you sure that you have sourced a `humble` version? I've just compiled the code with `humble` and `iron`, of course with the `rolling` branch

**Comment by tianjiawen1** [comment]
> @tianjiawen1 Are you sure that you have sourced a `humble` version? I've just compiled the code with `humble` and `iron`, of course with the `rolling` branch

thank you very much!  I'll check it tomorrow.

**Comment by tianjiawen1** [comment]
I had finished colcon build. but when i launch the controller, there was a error shows:
```
[ros2_control_node-1] [INFO] [1696318095.956253458] [resource_manager]: Loading hardware 'NetFtHardwareInterface' 
[ros2_control_node-1] [INFO] [1696318095.957246721] [resource_manager]: Initialize hardware 'NetFtHardwareInterface' 
[ros2_control_node-1] terminate called after throwing an instance of 'std::invalid_argument'
```
then the process has died

```
[ros2_control_node-1] Aborted (Signal sent by tkill() 79688 1000)
[ERROR] [ros2_control_node-1]: process has died [pid 79688, exit code -6, cmd '/opt/ros/humble/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_j6_9s99f --params-file /home/tian/tfsensor/install/net_ft_driver/share/net_ft_driver/config/net_ft_broadcaster.yaml'].
```
what should i do to fix it？
and i have ping the ip address of my sensor, it can be connected.

**Comment by tianjiawen1** [comment]
hello, 
the in file net_ft_broadcaster.launch.py, line 152 default value should be "0"
line 162 default value should be "flase"

**Comment by gbartyzel** [comment]
Foxy is now EOL.
